import { createContext, useContext } from "react";

export type RemotionLocale = "en" | "pt" | "es";

export const STRINGS = {
  en: {
    nav: {
      dashboard: "Dashboard",
      myPatients: "My Patients",
      learningPaths: "Learning Paths",
      reports: "Reports",
      recordingReviews: "Recording Reviews",
      exercises: "Exercises",
    },
    role: "Therapist",
    plan: {
      title: "Practice plan",
      subtitle: "Proposed from session data · adjusted by the therapist",
      assign: "Assign plan",
      assigned: "✓ Assigned to Miguel",
      scheduled: "Scheduled",
      pending: "Pending",
      reassurance: "No plan is assigned without therapist review.",
      exercises: [
        {
          cat: "Communication Strategies",
          title: "Guided Pauses - Medium",
          meta: "2 sec pauses",
        },
        {
          cat: "Stay in the Moment",
          title: "Holding - Natural Exit",
          meta: "3 sec exit",
        },
        { cat: "Scenario", title: "Ordering", meta: "Conversation practice" },
      ],
    },
    practice: {
      days: ["M", "T", "W", "T", "F", "S", "S"],
      eyebrow: "Tonight's practice · from your therapist",
      technique: "Holding - Natural Exit",
      quotePre: "When a block comes, hold the position calmly, ",
      quoteBold: "then release into the word with less tension.",
      recording: "Recording your attempt",
      sent: "✓ Sent to your therapist",
      attempt: "Attempt 3 of 5",
      footer: "Reviewed and adjusted by your therapist",
    },
    progress: {
      title: "Miguel A. · This week",
      subtitle: "Activity since the last session",
      nextSession: "Next session: Thursday",
      stats: [
        "Practice days",
        "Exercises done",
        "Practice time",
        "Self check-ins",
      ],
      dailyPractice: "Daily practice",
      monToSun: "Mon to Sun",
    },
    recording: {
      title: "Session recording",
      subtitle: "Miguel A. · Weekly session",
      saved: "✓ Saved · 32 min",
      steps: ["Recording uploaded", "Transcribed", "Notes drafted"],
      after: "After the session",
      from: "From this recording",
      tags: ["Transcript", "Draft notes", "Practice ideas"],
    },
    report: {
      title: "Session report",
      subtitle: "Drafted from today's session · Miguel A.",
      ready: "✓ Ready",
      draft: "Draft",
      sections: ["Session summary", "What we practised", "Recommendations"],
      reassurance: "Nothing leaves the platform without therapist review.",
      readyToShare: "✓ Ready to share",
      markReady: "Mark as ready",
    },
    annotation: {
      labs: "UpSpeech Labs",
      headline: "Clinician-annotated, frame by frame",
      annotating: "Annotating",
      tagged: "Tagged moments",
      tags: ["Block", "Prolongation", "Repetition", "Tension", "Holding"],
      clinician: "Sarah Johnson, SLP",
      body: "Speech-language pathologists label every recording by hand. The dataset is expert-annotated from the start.",
    },
    end: { line1: "The clinic that's open ", line2: "when you're not." },
  },
  pt: {
    nav: {
      dashboard: "Painel",
      myPatients: "Meus Pacientes",
      learningPaths: "Percursos de Aprendizagem",
      reports: "Relatórios",
      recordingReviews: "Revisão de Gravações",
      exercises: "Exercícios",
    },
    role: "Terapeuta",
    plan: {
      title: "Plano de prática",
      subtitle:
        "Proposto a partir dos dados da sessão · ajustado pelo terapeuta",
      assign: "Atribuir plano",
      assigned: "✓ Atribuído a Miguel",
      scheduled: "Agendado",
      pending: "Pendente",
      reassurance: "Nenhum plano é atribuído sem revisão do terapeuta.",
      exercises: [
        {
          cat: "Estratégias de Comunicação",
          title: "Pausas Guiadas - Médio",
          meta: "Pausas de 2 s",
        },
        {
          cat: "Ficar no Momento",
          title: "Retenção - Saída Natural",
          meta: "Saída de 3 s",
        },
        {
          cat: "Cenário",
          title: "Fazer um Pedido",
          meta: "Prática de conversação",
        },
      ],
    },
    practice: {
      days: ["S", "T", "Q", "Q", "S", "S", "D"],
      eyebrow: "Prática de hoje à noite · do teu terapeuta",
      technique: "Retenção - Saída Natural",
      quotePre: "Quando surge um bloqueio, mantém a posição com calma e ",
      quoteBold: "depois solta para a palavra com menos tensão.",
      recording: "A gravar a tua tentativa",
      sent: "✓ Enviado ao teu terapeuta",
      attempt: "Tentativa 3 de 5",
      footer: "Revisto e ajustado pelo teu terapeuta",
    },
    progress: {
      title: "Miguel A. · Esta semana",
      subtitle: "Atividade desde a última sessão",
      nextSession: "Próxima sessão: quinta-feira",
      stats: [
        "Dias de prática",
        "Exercícios feitos",
        "Tempo de prática",
        "Auto-registos",
      ],
      dailyPractice: "Prática diária",
      monToSun: "Seg a Dom",
    },
    recording: {
      title: "Gravação da sessão",
      subtitle: "Miguel A. · Sessão semanal",
      saved: "✓ Guardado · 32 min",
      steps: ["Gravação carregada", "Transcrito", "Notas redigidas"],
      after: "Depois da sessão",
      from: "A partir desta gravação",
      tags: ["Transcrição", "Rascunho de notas", "Ideias de prática"],
    },
    report: {
      title: "Relatório da sessão",
      subtitle: "Redigido a partir da sessão de hoje · Miguel A.",
      ready: "✓ Pronto",
      draft: "Rascunho",
      sections: ["Resumo da sessão", "O que praticámos", "Recomendações"],
      reassurance: "Nada sai da plataforma sem revisão do terapeuta.",
      readyToShare: "✓ Pronto para partilhar",
      markReady: "Marcar como pronto",
    },
    annotation: {
      labs: "UpSpeech Labs",
      headline: "Anotado por clínicos, fotograma a fotograma",
      annotating: "A anotar",
      tagged: "Momentos marcados",
      tags: ["Bloqueio", "Prolongamento", "Repetição", "Tensão", "Retenção"],
      clinician: "Sarah Johnson, Terapeuta da Fala",
      body: "Os terapeutas da fala etiquetam cada gravação manualmente. O conjunto de dados é anotado por especialistas desde o início.",
    },
    end: {
      line1: "A clínica que continua aberta ",
      line2: "mesmo quando fecha.",
    },
  },
  es: {
    nav: {
      dashboard: "Panel de Control",
      myPatients: "Mis Pacientes",
      learningPaths: "Rutas de Aprendizaje",
      reports: "Informes",
      recordingReviews: "Revisión de Grabaciones",
      exercises: "Ejercicios",
    },
    role: "Terapeuta",
    plan: {
      title: "Plan de práctica",
      subtitle:
        "Propuesto a partir de los datos de la sesión · ajustado por el terapeuta",
      assign: "Asignar plan",
      assigned: "✓ Asignado a Miguel",
      scheduled: "Programado",
      pending: "Pendiente",
      reassurance: "Ningún plan se asigna sin revisión del terapeuta.",
      exercises: [
        {
          cat: "Estrategias de Comunicación",
          title: "Pausas Guiadas - Medio",
          meta: "Pausas de 2 s",
        },
        {
          cat: "Quedarse en el Momento",
          title: "Retención - Salida Natural",
          meta: "Salida de 3 s",
        },
        {
          cat: "Escenario",
          title: "Hacer un Pedido",
          meta: "Práctica de conversación",
        },
      ],
    },
    practice: {
      days: ["L", "M", "X", "J", "V", "S", "D"],
      eyebrow: "Práctica de esta noche · de tu terapeuta",
      technique: "Retención - Salida Natural",
      quotePre: "Cuando llega un bloqueo, mantén la posición con calma y ",
      quoteBold: "luego suéltate hacia la palabra con menos tensión.",
      recording: "Grabando tu intento",
      sent: "✓ Enviado a tu terapeuta",
      attempt: "Intento 3 de 5",
      footer: "Revisado y ajustado por tu terapeuta",
    },
    progress: {
      title: "Miguel A. · Esta semana",
      subtitle: "Actividad desde la última sesión",
      nextSession: "Próxima sesión: jueves",
      stats: [
        "Días de práctica",
        "Ejercicios hechos",
        "Tiempo de práctica",
        "Autorregistros",
      ],
      dailyPractice: "Práctica diaria",
      monToSun: "Lun a Dom",
    },
    recording: {
      title: "Grabación de la sesión",
      subtitle: "Miguel A. · Sesión semanal",
      saved: "✓ Guardado · 32 min",
      steps: ["Grabación subida", "Transcrito", "Notas redactadas"],
      after: "Después de la sesión",
      from: "A partir de esta grabación",
      tags: ["Transcripción", "Borrador de notas", "Ideas de práctica"],
    },
    report: {
      title: "Informe de la sesión",
      subtitle: "Redactado a partir de la sesión de hoy · Miguel A.",
      ready: "✓ Listo",
      draft: "Borrador",
      sections: [
        "Resumen de la sesión",
        "Lo que practicamos",
        "Recomendaciones",
      ],
      reassurance: "Nada sale de la plataforma sin revisión del terapeuta.",
      readyToShare: "✓ Listo para compartir",
      markReady: "Marcar como listo",
    },
    annotation: {
      labs: "UpSpeech Labs",
      headline: "Anotado por clínicos, fotograma a fotograma",
      annotating: "Anotando",
      tagged: "Momentos etiquetados",
      tags: ["Bloqueo", "Prolongación", "Repetición", "Tensión", "Retención"],
      clinician: "Sarah Johnson, Logopeda",
      body: "Los logopedas etiquetan cada grabación a mano. El conjunto de datos está anotado por expertos desde el principio.",
    },
    end: {
      line1: "La clínica que sigue abierta ",
      line2: "cuando tú no estás.",
    },
  },
} as const;

export const LocaleContext = createContext<RemotionLocale>("en");
export const useStrings = () => STRINGS[useContext(LocaleContext)];
