// Generated by tools/subject-lift/build-cutouts.sh. Do not edit.
// Intrinsic size of each cut-out, so <img> can reserve its box.
export const CUTOUTS: Record<string, { w: number; h: number }> = {
  "day-notes": { w: 900, h: 680 },
  "day-present": { w: 900, h: 631 },
  "home-family": { w: 900, h: 759 },
  "patients-hero": { w: 900, h: 785 },
  "patients-listen": { w: 900, h: 951 },
  "slps-family": { w: 900, h: 966 },
  "slps-hero": { w: 900, h: 1167 },
  "week-alone": { w: 900, h: 851 },
  "week-next": { w: 900, h: 878 },
  "week-phone": { w: 900, h: 1766 },
  "week-session": { w: 900, h: 981 },
};
