// Generated by tools/subject-lift/build-cutouts.sh. Do not edit.
// Intrinsic size of each cut-out, so <img> can reserve its box.
export const CUTOUTS: Record<string, { w: number; h: number }> = {
  "day-notes": { w: 900, h: 680 },
  "day-present": { w: 900, h: 631 },
  "home-family": { w: 900, h: 644 },
  "patients-hero": { w: 900, h: 785 },
  "patients-listen": { w: 900, h: 1127 },
  "practice-hero-1536": { w: 900, h: 973 },
  "practice-hero": { w: 900, h: 1056 },
  "slps-family": { w: 900, h: 966 },
  "slps-hero": { w: 900, h: 1237 },
  "week-alone": { w: 900, h: 851 },
  "week-next": { w: 900, h: 865 },
  "week-phone": { w: 900, h: 1362 },
  "week-session": { w: 900, h: 732 },
};
