// Generated by tools/subject-lift/build-cutouts.sh. Do not edit.
// Intrinsic size of each cut-out, so <img> can reserve its box.
export const CUTOUTS: Record<string, { w: number; h: number }> = {
  "day-notes": { w: 900, h: 681 },
  "day-present": { w: 900, h: 632 },
  "home-family": { w: 900, h: 647 },
  "patients-hero": { w: 900, h: 788 },
  "patients-listen": { w: 900, h: 1121 },
  "practice-hero": { w: 900, h: 1052 },
  "slps-family": { w: 900, h: 969 },
  "slps-hero": { w: 900, h: 1525 },
  "week-alone": { w: 900, h: 851 },
  "week-next": { w: 900, h: 868 },
  "week-phone": { w: 900, h: 1353 },
  "week-session": { w: 900, h: 735 },
};
