// AUTO-GENERATED by scripts/generate-route-dates.mjs. Do not edit by hand.
// Run `npm run dates:routes` (or a build) to regenerate.
// Each entry is a locale-agnostic route path and the date of the most recent
// commit touching that page's component or anything it imports.

export const ROUTE_DATES: Readonly<Record<string, string>> = {
  "/": "2026-08-25",
  "/techniques": "2026-08-25",
  "/techniques/voluntary-stuttering": "2026-08-25",
  "/techniques/cancelation": "2026-08-25",
  "/techniques/pull-out": "2026-08-25",
  "/techniques/preparatory-set": "2026-08-25",
  "/techniques/holding": "2026-08-25",
  "/techniques/soft-starts": "2026-08-25",
  "/techniques/soft-articulation-contact": "2026-08-25",
  "/techniques/prolonged-speech": "2026-08-25",
  "/techniques/speech-speed-management": "2026-08-25",
  "/techniques/pauses": "2026-08-25",
  "/techniques/identification-desensitization": "2026-08-25",
  "/for-patients": "2026-08-25",
  "/person-centered-therapy": "2026-08-25",
  "/reducing-documentation-time": "2026-08-25",
  "/for-slps": "2026-08-25",
  "/support": "2026-08-25",
  "/privacy": "2026-08-25",
  "/terms": "2026-08-25",
  "/cookies": "2026-08-25",
  "/delete-account": "2026-08-20",
};

/** dateModified for a route, or undefined when git history was unavailable. */
export function routeDate(path: string): string | undefined {
  const key = path === "" ? "/" : path.replace(/\/$/, "") || "/";
  return ROUTE_DATES[key];
}
