// AUTO-GENERATED by scripts/generate-asset-manifest.mjs. Do not edit by hand.
// Run `npm run manifest:assets` (or a build) to regenerate.
// Each entry is "<locale>|<english base path>" for a localized asset that exists
// under public/. The resolver in ./assets.ts uses it to decide fallback.

export const LOCALIZED_ASSETS: ReadonlySet<string> = new Set([
  "es|/screenshots/app/cbsa-severity-trend.png",
  "es|/screenshots/app/client-dashboard.png",
  "es|/screenshots/app/therapist-dashboard.png",
  "es|/screenshots/app/therapist-learning-path.png",
  "es|/screenshots/app/therapist-patient-progress.jpg",
  "es|/screenshots/app/therapist-report.png",
  "es|/screenshots/desktop.jpg",
  "es|/screenshots/mobile/patient-home-device.webp",
  "es|/screenshots/mobile/patient-journey-device.webp",
  "es|/screenshots/mobile/patient-practice-device.webp",
  "es|/videos/hero-demo-poster.webp",
  "es|/videos/hero-demo.mp4",
  "pt|/screenshots/app/cbsa-severity-trend.png",
  "pt|/screenshots/app/client-dashboard.png",
  "pt|/screenshots/app/therapist-dashboard.png",
  "pt|/screenshots/app/therapist-learning-path.png",
  "pt|/screenshots/app/therapist-patient-progress.jpg",
  "pt|/screenshots/app/therapist-report.png",
  "pt|/screenshots/desktop.jpg",
  "pt|/screenshots/mobile/patient-home-device.webp",
  "pt|/screenshots/mobile/patient-journey-device.webp",
  "pt|/screenshots/mobile/patient-practice-device.webp",
  "pt|/videos/hero-demo-poster.webp",
  "pt|/videos/hero-demo.mp4",
]);
