// AUTO-GENERATED by scripts/generate-asset-manifest.mjs. Do not edit by hand.
// Run `npm run manifest:assets` (or a build) to regenerate.
// Each entry is "<locale>|<english base path>" for a localized asset that exists
// under public/. The resolver in ./assets.ts uses it to decide fallback.

export const LOCALIZED_ASSETS: ReadonlySet<string> = new Set([

]);
