#!/bin/bash
#
# Build the alpha cut-outs in public/images/people/cut/ from the framed
# photographs beside them.
#
# Run by hand on macOS, not in CI: the segmentation is Vision's
# VNGenerateForegroundInstanceMaskRequest, which is the same model behind
# lifting a subject in Photos. It needs macOS 14+ and a Swift toolchain, and it
# is the reason no paid background-removal service is in the loop. The outputs
# are committed, so a normal build never runs this.
#
#   ./tools/subject-lift/build-cutouts.sh            # every subject below
#   ./tools/subject-lift/build-cutouts.sh week-phone # just one
#
# Requires: swiftc, ImageMagick (magick), cwebp.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
SRC="$ROOT/public/images/people"
OUT="$SRC/cut"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# Exposure target, as mean luminance over opaque pixels on a 0-100 scale.
# Chosen as the median of the set as originally shot. Matching to it is what
# stops a row of cut-outs reading as a stock collage: before this the set ran
# from 12 to 38, and the darkest subject was three times darker than the rest.
TARGET=31

SUBJECTS=(
  week-session week-alone week-phone week-next
  day-notes day-present
  home-family
  patients-hero patients-listen
  slps-hero slps-family
)

for bin in swiftc magick cwebp; do
  command -v "$bin" >/dev/null || { echo "missing $bin" >&2; exit 1; }
done

echo "building lift..."
swiftc -O -o "$TMP/lift" "$HERE/lift.swift"
mkdir -p "$OUT"

list=("${@:-}")
[ -z "${list[0]:-}" ] && list=("${SUBJECTS[@]}")

printf "%-18s %-8s %-8s %s\n" subject gamma bright size
for n in "${list[@]}"; do
  in="$SRC/$n.webp"
  [ -f "$in" ] || { echo "  no source for $n" >&2; continue; }

  # 1. lift the subject out of its background
  magick "$in" "$TMP/in.png"
  "$TMP/lift" "$TMP/in.png" "$TMP/a.png" >/dev/null

  # 2. warm grade: the source set is flat, cool and evenly lit, which is most
  #    of what reads as sterile once the background is gone
  magick "$TMP/a.png" \( +clone -alpha extract -write mpr:A +delete \) -alpha off \
    -modulate 103,108,100 -sigmoidal-contrast 3.2,48% -fill "#ffd9a8" -colorize 6 \
    -attenuate 0.30 +noise Gaussian mpr:A -compose CopyOpacity -composite "$TMP/b.png"

  # 3. match exposure to the set. Measured over opaque pixels only: a mean over
  #    the whole canvas measures how much of the frame the subject fills, not
  #    how it is lit.
  GA=$(magick "$TMP/b.png" \( +clone -alpha extract \) -alpha off -colorspace Gray \
        -compose Multiply -composite -format "%[fx:mean]" info:)
  AV=$(magick "$TMP/b.png" -alpha extract -format "%[fx:mean]" info:)
  read -r G BEFORE <<<"$(python3 -c "
import math
cur = 100*$GA/max($AV,1e-6)
g = 1/(math.log($TARGET/100)/math.log(max(cur,1)/100))
print(f'{min(max(g,0.75),1.95):.3f} {cur:.1f}')")"
  magick "$TMP/b.png" \( +clone -alpha extract -write mpr:B +delete \) -alpha off \
    -gamma "$G" mpr:B -compose CopyOpacity -composite "$TMP/c.png"

  # 4. erode one pixel of matte. A subject cut from a light background carries
  #    that light in its edge pixels, which shows as a fringe on the navy band.
  magick "$TMP/c.png" -channel A -morphology Erode Disk:1 +channel -trim +repage "$TMP/d.png"

  # 5. dissolve the base into the ground. This is baked into the alpha rather
  #    than done with a CSS mask on purpose: filter runs before mask, so a
  #    masked element still casts the shadow of its unmasked silhouette and it
  #    shows through the faded region as a grey rectangle.
  for w in 900 560; do
    magick "$TMP/d.png" -resize "${w}x" "$TMP/r.png"
    W=$(magick identify -format %w "$TMP/r.png"); H=$(magick identify -format %h "$TMP/r.png")
    F=$(( H * 22 / 100 ))
    magick "$TMP/r.png" \
      \( +clone -alpha extract \
         \( -size "${W}x${H}" xc:white \
            \( -size "${W}x${F}" gradient:white-black \) -gravity south -composite \) \
         -compose Multiply -composite \) \
      -alpha off -compose CopyOpacity -composite "$TMP/f.png"
    suffix=""; [ "$w" = 560 ] && suffix="-560"
    cwebp -quiet -q 80 -alpha_q 92 -m 6 "$TMP/f.png" -o "$OUT/$n$suffix.webp"
  done

  GA2=$(magick "$OUT/$n.webp" \( +clone -alpha extract \) -alpha off -colorspace Gray \
         -compose Multiply -composite -format "%[fx:mean]" info:)
  AV2=$(magick "$OUT/$n.webp" -alpha extract -format "%[fx:mean]" info:)
  AFTER=$(python3 -c "print(f'{100*$GA2/max($AV2,1e-6):.1f}')")
  printf "%-18s %-8s %-8s %sK\n" "$n" "$G" "$BEFORE->$AFTER" \
    "$(( $(stat -f%z "$OUT/$n.webp")/1024 ))"
done

# A cut-out is trimmed to its subject, so every one has its own intrinsic size
# and the component cannot guess it. Emit the dimensions so <img width/height>
# can reserve the right box and the row does not jump on load.
echo "writing src/lib/cutouts.generated.ts"
{
  echo "// Generated by tools/subject-lift/build-cutouts.sh. Do not edit."
  echo "// Intrinsic size of each cut-out, so <img> can reserve its box."
  echo "export const CUTOUTS: Record<string, { w: number; h: number }> = {"
  for f in "$OUT"/*.webp; do
    b="$(basename "$f" .webp)"
    case "$b" in *-560) continue;; esac
    read -r W H <<<"$(magick identify -format "%w %h" "$f")"
    echo "  \"$b\": { w: $W, h: $H },"
  done
  echo "};"
} > "$ROOT/src/lib/cutouts.generated.ts"
